# see https://docs.github.com/en/code-security/supply-chain-security/enabling-and-disabling-version-updates

version: 2
updates:
  # Enable version updates for pip
  - package-ecosystem: pip
    # Look for `requirements.txt` in the `root` directory
    directory: /
    schedule:
      interval: weekly
      day: saturday

  # Maintain dependencies for GitHub Actions
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: saturday
