dist: focal
language: python
cache: pip
python:
  - "3.9"
  - "3.8"
  - "3.7"
  - "3.6"
install:
  - pip install --upgrade pip setuptools wheel
  - pip install -r requirements.txt
  - pip install flake8 pytest
  - pip install backports.zoneinfo;python_version<"3.9"
script:
  - pytest test.py
