dist: focal
language: python
cache: pip
python:
  - "3.9"
  - "3.8"
  - "3.7"
  - "3.6"
install:
  - pip install --upgrade pip setuptools
  - pip install flake8 flake8-import-order pytest typing_extensions
script:
  - pytest test.py
